remote_theme: pages-themes/slate@v0.2.0
baseurl: https://oyanzhi.github.io/ip/
title: TrackerBot
description: This is a CLI/GUI enabled application that allows users to manage their tasks.
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
